export const xx = [
  {
    id: "b81b89757cdfeb35cd80bb5d42907c0c",
    firstName: "Karen",
    lastName: "Darbinyan",
    phone: "+374 98 156 247",
    email: "kar31100@gmail.com",
    education: "YSU",
    workExperience: "alam asxarh",
    trainings: "RELQ",
    imagePath: "./Img/Karen.jpg",
  },
  {
    id: "8c1a86e9f5dcb6098b399d6ffa119cd2",
    firstName: "Alexandr",
    lastName: "Hamabrdzumyan",
    phone: "+374 98 156 247",
    email: "kar31100@gmail.com",
    education: "YSU",
    workExperience: "alam asxarh",
    trainings: "RELQ",
    imagePath: "./Img/Alexandr.jpg",
  },
  {
    id: "ab98fa0c049dc1e9c736ae5e2445c171",
    firstName: "Hasmik",
    lastName: "Gevorgyan",
    phone: "+374 98 156 247",
    email: "kar31100@gmail.com",
    education: "YSU",
    workExperience: "alam asxarh",
    trainings: "RELQ",
    imagePath: "./Img/Hasmik.jpg",
  },
  {
    id: "ebbcf5652a40ffebcbea2a24a9a76b82",
    firstName: "Lusine",
    lastName: "Yeremyan",
    phone: "+374 98 156 247",
    email: "kar31100@gmail.com",
    education: "YSU",
    workExperience: "alam asxarh",
    trainings: "RELQ",
    imagePath: "./Img/Lusine.jpg",
  },
  {
    id: "ecb857bfba55c868f5a69142902a3312",
    firstName: "Anahit",
    lastName: "Khechumyan",
    phone: "+374 98 156 247",
    email: "kar31100@gmail.com",
    education: "YSU",
    workExperience: "alam asxarh",
    trainings: "RELQ",
    imagePath: "./Img/Anahit.jpg",
  },
  {
    id: "fc6be5e05ae1e298cfc46daffc3e7193",
    firstName: "Ani",
    lastName: "Antonyan",
    phone: "+374 41 55 51 52",
    email: "notDefined",
    education: "notDefined",
    workExperience: "notDefined",
    trainings: "RELQ",
    imagePath: "./Img/Ani.jpg",
  },
  {
    id: "fbea58a180984456da150c8e94293893",
    firstName: "Anna",
    lastName: "Hayriyan",
    phone: "+374 98 14 44 50",
    email: "annhayriyan@gmail.com",
    education: "ASUE",
    workExperience: "Scott logistics",
    trainings: "RELQ",
    imagePath: "./Img/person-icon.jpg",
  },
  {
    id: "f066197adfdcb706e7715700351de283",
    firstName: "Armenak",
    lastName: "Qocharyan",
    phone: "+374 94 90 21 71",
    email: "qocharyanarmenak@gmail.com",
    education: "Բարձրագույն զինվորական",
    workExperience: "ՀՀ ՊՆ",
    trainings: "Relq School",
    imagePath: "./Img/Armenak.jpg",
  },
  {
    id: "f51f2d239d20bec089d0d4a4a152f018",
    firstName: "Arusyak",
    lastName: "Aghajanyan",
    phone: "+374 55 90 01 55",
    email: "aghajanyanarusyak@gmail.com",
    education: "YSUGU",
    workExperience: "InecoBank CJSC, Risk meneger",
    trainings:
      "BasicItCenter,UNDP Armenia Accelerator5,HTI Armenia C++ basic, SmartCode,Relq Technology",
    imagePath: "./Img/Arusyak.jpg",
  },
  {
    id: "ead015900d434dd6ff0b83fa0cc6dc61",
    firstName: "Afina",
    lastName: "Panyan",
    phone: "+374 96 33 33 28",
    email: "notDefined",
    education: "notDefined",
    workExperience: "notDefined",
    trainings: "Relq",
    imagePath: "./Img/person-icon.jpg",
  },
  {
    id: "975bec89260cceafbcaca6c0c3b3a0e0",
    firstName: "Babken",
    lastName: "Tadevosyan",
    phone: "+374 93 28 55 95",
    email: "notDefined",
    education: "notDefined",
    workExperience: "notDefined",
    trainings: "Relq",
    imagePath: "./Img/person-icon.jpg",
  },
  {
    id: "f4dcf50cd0360e40beececeb69586471",
    firstName: "Hermine",
    lastName: "Melkumyan",
    phone: "+374 49 26 65 99",
    email: "notDefined",
    education: "notDefined",
    workExperience: "notDefined",
    trainings: "Relq",
    imagePath: "./Img/Hermine.jpg",
  },
  {
    id: "d181115832e31e4bc094815eba8e7d72",
    firstName: "Hermine",
    lastName: "Sahakyan",
    phone: "",
    email: "notDefined",
    education: "notDefined",
    workExperience: "notDefined",
    trainings: "Relq",
    imagePath: "./Img/person-icon.jpg",
  },
  {
    id: "8085adfca7e75548bc6a71b78ced103d",
    firstName: "Larine",
    lastName: "Danielyan",
    phone: "+374 97 75 95 99",
    email: "danielyanlari@gmail.com",
    education: "Economics and Menegment",
    workExperience: "Martuninsky district Medical Association",
    trainings: "Relq",
    imagePath: "./Img/Larine.jpg",
  },
  {
    id: "cd9f86b4b752c743ac84ed7e1fe2a3b0",
    firstName: "Liana",
    lastName: "Dashyan",
    phone: "+374 91 55 53 74",
    email: "dashyanlian@gmail.com",
    education: "YSU",
    workExperience: "GYU NGO",
    trainings: "Relq",
    imagePath: "./Img/person-icon.jpg",
  },
  {
    id: "f87e8bd8c705b022b1ea3fccea6ba13a",
    firstName: "Lusya",
    lastName: "Petrosyan",
    phone: "+374 93 32 29 02",
    email: "plusine99@gmail.com",
    education: "Armenian State University faculty of Radiophysics",
    workExperience: "NASA",
    trainings: "Relq",
    imagePath: "./Img/Lusya.jpg",
  },
  {
    id: "bcf1963bed5d26f5eb5fffff7bec4c6f",
    firstName: "Marat",
    lastName: "Harutyunyan",
    phone: "+374 44 05 51 50",
    email: "maratharutyunyan.mh.mh@gmail.com",
    education: "ASIPCS",
    workExperience: "EL Market",
    trainings: "Relq School",
    imagePath: "./Img/Marat.jpg",
  },
  {
    id: "a12ac86cf0e875e5c37e3e756e0bbf58",
    firstName: "Narek",
    lastName: "Tovmasyan",
    phone: "+374 94 27 67 00",
    email: "Narektom333@gmail.com",
    education: "ASUE",
    workExperience: "Ameria Bank",
    trainings: "Relq School",
    imagePath: "./Img/Narek.jpg",
  },
  {
    id: "845a5d0e6f0e9f0d9cdd9aa037f69ba9",
    firstName: "Seda",
    lastName: "Shahnazaryan",
    phone: "+374 98 31 38 71",
    email: "shahnazaryan.seda@mail.ru",
    education: "Higher Education:Historian",
    workExperience: "notDefined",
    trainings: "TechBoost4Women,Relq technology school",
    imagePath: "./Img/Seda.jpg",
  },
  {
    id: "b0387697c537babac0a993a2218d9fc9",
    firstName: "Seryozha",
    lastName: "Asatryan",
    phone: "+374 94 24 68 80",
    email: "seryozha.asatryan02@gmail.com",
    education: "Economics",
    workExperience: "notDefined",
    trainings: "Relq School",
    imagePath: "./Img/Seryozha.jpg",
  },
  {
    id: "8aade1e294ac79558c8bcdff0908e9f6",
    firstName: "Sevak",
    lastName: "Stepanyan",
    phone: "+374 77 12 16 96",
    email: "stepanyansevak9@gamil.com",
    education: "Economics and Menegment",
    workExperience: "notDefined",
    trainings: "Relq School",
    imagePath: "./Img/person-icon.jpg",
  },
  {
    id: "c31f641cbb65b2fdc9bc2905f95505d9",
    firstName: "Silva",
    lastName: "Ohanyan",
    phone: "+374 98 20 02 72",
    email: "notDefined",
    education: "notDefined",
    workExperience: "notDefined",
    trainings: "Relq School",
    imagePath: "./Img/person-icon.jpg",
  },
  {
    id: "918041b28fedcaedb9522a8c3d648b79",
    firstName: "Suren",
    lastName: "Galstyan",
    phone: "+374 77 76 09 86",
    email: "notDefined",
    education: "notDefined",
    workExperience: "notDefined",
    trainings: "Relq School",
    imagePath: "./Img/person-icon.jpg",
  },
  {
    id: "f13984b40a62f30c8b3dcceff40af430",
    firstName: "Tigran",
    lastName: "Martirosyan",
    phone: "+374 77 15 18 68",
    email: "martirosyant01@mail.ru",
    education: "notDefined",
    workExperience: "notDefined",
    trainings: "Relq School",
    imagePath: "./Img/Tigran.jpg",
  },
];
